# Generated by Django 6.0.3 on 2026-07-05 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('slug', models.SlugField(unique=True, verbose_name='标识')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('icon', models.CharField(blank=True, help_text='使用 emoji', max_length=50, verbose_name='图标')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '宠物分类',
                'verbose_name_plural': '宠物分类',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='品种名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格(元)')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='图片链接')),
                ('description', models.TextField(verbose_name='品种介绍')),
                ('color', models.CharField(blank=True, max_length=200, verbose_name='常见毛色')),
                ('weight', models.CharField(blank=True, help_text='例如: 25-35kg', max_length=50, verbose_name='体重范围')),
                ('height', models.CharField(blank=True, help_text='例如: 55-65cm', max_length=50, verbose_name='肩高范围')),
                ('lifespan', models.CharField(blank=True, help_text='例如: 10-12年', max_length=50, verbose_name='寿命')),
                ('temperament', models.TextField(blank=True, verbose_name='性格特点')),
                ('origin', models.CharField(blank=True, max_length=100, verbose_name='原产地')),
                ('is_popular', models.BooleanField(default=False, verbose_name='是否热门')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否上架')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='pets.petcategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '狗狗',
                'verbose_name_plural': '狗狗',
                'ordering': ['-is_popular', '-created_at'],
            },
        ),
    ]
