# Generated by Django 6.0.3 on 2026-07-20 07:40

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='宠物昵称')),
                ('species', models.CharField(choices=[('dog', '🐶 狗狗'), ('cat', '🐱 猫咪'), ('rabbit', '🐰 兔子'), ('bird', '🐦 小鸟'), ('fish', '🐟 鱼类'), ('hamster', '🐹 仓鼠'), ('turtle', '🐢 乌龟'), ('other', '其他')], default='dog', max_length=20, verbose_name='物种')),
                ('breed', models.CharField(blank=True, help_text='如：金毛、布偶猫', max_length=100, verbose_name='品种')),
                ('gender', models.CharField(choices=[('male', '♂️ 男生'), ('female', '♀️ 女生')], default='male', max_length=10, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('adopted_date', models.DateField(blank=True, null=True, verbose_name='领养/接回家日期')),
                ('avatar_url', models.URLField(blank=True, max_length=500, verbose_name='头像链接')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='毛色/特征')),
                ('microchip_id', models.CharField(blank=True, max_length=50, verbose_name='芯片编号')),
                ('notes', models.TextField(blank=True, help_text='过敏史、特殊习惯等', verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在养')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='主人')),
            ],
            options={
                'verbose_name': '宠物档案',
                'verbose_name_plural': '宠物档案',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deworming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deworming_type', models.CharField(choices=[('internal', '体内驱虫'), ('external', '体外驱虫'), ('both', '体内外同驱')], max_length=10, verbose_name='驱虫类型')),
                ('product_name', models.CharField(blank=True, help_text='如：大宠爱、福来恩', max_length=100, verbose_name='驱虫药名称')),
                ('administered_date', models.DateField(verbose_name='驱虫日期')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='下次驱虫日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dewormings', to='pets.petprofile', verbose_name='宠物')),
            ],
            options={
                'verbose_name': '驱虫记录',
                'verbose_name_plural': '驱虫记录',
                'ordering': ['-administered_date'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('vaccination', '💉 疫苗接种'), ('deworming', '🪱 驱虫'), ('nails', '💅 剪指甲'), ('bath', '🛁 洗澡'), ('grooming', '✂️ 美容'), ('checkup', '🏥 体检'), ('teeth', '🦷 刷牙/洁牙'), ('weight', '⚖️ 称体重'), ('feed', '🍖 换粮/补货'), ('custom', '📌 自定义')], max_length=20, verbose_name='提醒类型')),
                ('title', models.CharField(max_length=100, verbose_name='提醒标题')),
                ('description', models.TextField(blank=True, verbose_name='详细说明')),
                ('reminder_date', models.DateField(verbose_name='提醒日期')),
                ('repeat_interval_days', models.IntegerField(blank=True, help_text='留空则不重复', null=True, verbose_name='重复间隔(天)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否已完成')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='pets.petprofile', verbose_name='宠物')),
            ],
            options={
                'verbose_name': '日程提醒',
                'verbose_name_plural': '日程提醒',
                'ordering': ['reminder_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_type', models.CharField(choices=[('rabies', '狂犬疫苗'), ('dhpp', '犬瘟/细小/肝炎/副流感四联'), ('dhpp_plus', '犬八联疫苗'), ('fvrpc', '猫三联(猫瘟/猫鼻支/猫杯状)'), ('felv', '猫白血病疫苗'), ('other', '其他疫苗')], max_length=20, verbose_name='疫苗类型')),
                ('vaccine_name', models.CharField(blank=True, help_text='如：卫佳伍、妙三多', max_length=100, verbose_name='疫苗名称')),
                ('dose_number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='第几针')),
                ('administered_date', models.DateField(verbose_name='接种日期')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='下次接种日期')),
                ('clinic', models.CharField(blank=True, max_length=100, verbose_name='接种医院/诊所')),
                ('veterinarian', models.CharField(blank=True, max_length=50, verbose_name='兽医姓名')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='pets.petprofile', verbose_name='宠物')),
            ],
            options={
                'verbose_name': '疫苗接种',
                'verbose_name_plural': '疫苗接种',
                'ordering': ['-administered_date'],
            },
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='体重(kg)')),
                ('recorded_at', models.DateField(default=datetime.date.today, verbose_name='记录日期')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='pets.petprofile', verbose_name='宠物')),
            ],
            options={
                'verbose_name': '体重记录',
                'verbose_name_plural': '体重记录',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
