# Generated by Django 6.0.3 on 2026-09-08 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0004_product_productcategory_cart_order_orderitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="dog",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="pets.dog",
                verbose_name="狗狗",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="dog",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pets.dog",
                verbose_name="狗狗",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pets.product",
                verbose_name="产品",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pets.product",
                verbose_name="产品",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dog__isnull", False)),
                fields=("cart", "dog"),
                name="unique_cart_dog",
            ),
        ),
    ]
